### ISSUE TITLE
Error when using -r 

### ISSUE THREAD

**Issue by eeucalyptus** [robertlipe/svdtoheaders#1]
Hi, when I try using the -r flag to generate the register header, I get an error 

```
$ svdtoheaders -s AT32F403Axx_v2.svd -p "" -r AT32F403Axx_registers.h -o
Traceback (most recent call last):
  File "/home/eike/.local/bin/svdtoheaders", line 238, in <module>
    main()
  File "/home/eike/.local/bin/svdtoheaders", line 234, in main
    for r in (registers(doc)):
  File "/home/eike/.local/bin/svdtoheaders", line 118, in registers
    fields = register.get('fields', {}).get('field', [])
AttributeError: 'NoneType' object has no attribute 'get'
$ 
```

I'm using this SVD: https://raw.githubusercontent.com/vadrov/AT32F403ACGU7_display_spi_dma_st7789_ili9341/main/SVD/AT32F403Axx_v2.svd

**Comment by robertlipe** [comment]
There's something in that svd file we're not expecting. Please include it
or a reduced case that repros the problem.

**Comment by eeucalyptus** [comment]
I'm not exacty sure what you mean. I was able to pinpoint the error to the register "PSR", which is defined as 
```
        <register>
          <name>PSR</name>
          <displayName>PSR</displayName>
          <description>Performance selection register</description>
          <addressOffset>0x0</addressOffset>
          <size>0x20</size>
          <resetValue>0x00000030</resetValue>
          <fields>
          </fields>
        </register>
```

in contrast to all other registers, the "\<fields\>" section is empty. I don't know about the svd standard, but in xml that's completely valid. 

My suggestion would be to add a sanity check there. I can also add a pull request if that's of interest.

BTW my workaround was to add a field "reserved" which was 32 bit long

**Comment by robertlipe** [comment]
You didn't include that, so I don't know how I was supposed to guess that.
I don't know what 'the "" section' means.

If you spot what makes that file unique, please submit a PR that works with
your files. Since you're literally issue #1 with this problem since it was
published, it's not like it's been exposed (to my knowledge) to thousands
of SVDs and the rich, creative ways I'm sure that vendors have found to
make them squirrely.

Thank you.

**Comment by eeucalyptus** [comment]
Alright I see where their initial miscommunication came from, I had to edit my description because I didn't escape the brackets in the first place and updates don't seem to be sent via email :D also the link to the svd file seems to be affected, hence the confusion 

Okay I'll submit a PR when I find the time for a fix

**Comment by robertlipe** [comment]
Fixed in 7be9ce7
